#! /bin/sh
test "${ZSH_VERSION+set}" = set && alias -g '${1+"$@"}'='"$@"'
cd '/cygdrive/c/OC/gnucobol-2.2/tests'
exec ${CONFIG_SHELL-/bin/sh} "/cygdrive/c/OC/gnucobol-2.2/tests/./testsuite" -v -d  518 ${1+"$@"}
exit 1
